export class GameModel {
  constructor(){this.difficulty='Easy';this.level=1;this.lives=3;this.hintStage=0;const saved=Number(localStorage.getItem('sequenceIQ.hints'));this.hints=Number.isInteger(saved)&&saved>=0?saved:3;this.completed=this.readJSON('sequenceIQ.completed',{});this.music=localStorage.getItem('sequenceIQ.music')!=='false';this.sound=localStorage.getItem('sequenceIQ.sound')!=='false';this.puzzles={Easy:[],Hard:[],Master:[]};}
  readJSON(k,f){try{const v=JSON.parse(localStorage.getItem(k)||'null');return v&&typeof v==='object'&&!Array.isArray(v)?v:f;}catch{return f;}}
  save(){localStorage.setItem('sequenceIQ.completed',JSON.stringify(this.completed));localStorage.setItem('sequenceIQ.hints',String(this.hints));localStorage.setItem('sequenceIQ.music',String(this.music));localStorage.setItem('sequenceIQ.sound',String(this.sound));}
  async loadPuzzles(){const response=await fetch('Puzzles.txt?v=5',{cache:'no-store'});if(!response.ok)throw new Error(`Puzzles.txt HTTP ${response.status}`);const text=await response.text();const seen=new Set();this.puzzles={Easy:[],Hard:[],Master:[]};for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(!line||line.startsWith('#'))continue;const parts=line.split('|');if(parts.length!==5)throw new Error(`Invalid puzzle row: ${line}`);const[id,difficulty,seq,opts,answer]=parts;if(!this.puzzles[difficulty]||seen.has(id))throw new Error(`Invalid/duplicate puzzle: ${id}`);const sequence=seq.split(',').map(v=>v.trim()==='?'?null:Number(v.trim()));const options=opts.split(',').map(v=>Number(v.trim()));const correct=Number(answer.trim());const uniqueOptions=new Set(options);if(!/^[EHM]\d{2}$/.test(id)||options.length!==4||uniqueOptions.size!==4||options.filter(v=>v===correct).length!==1||sequence.length!==6||sequence.filter(v=>v===null).length!==1||sequence.some(v=>v!==null&&Number.isNaN(v))||options.some(Number.isNaN)||Number.isNaN(correct))throw new Error(`Invalid puzzle data: ${id}`);seen.add(id);this.puzzles[difficulty].push({id,sequence,options,answer:correct});}for(const d of ['Easy','Hard','Master'])if(this.puzzles[d].length!==20)throw new Error(`${d} must contain exactly 20 puzzles`);}
  key(d=this.difficulty,l=this.level){return `${d}-${l}`;}
  countDone(d){return Object.keys(this.completed).filter(k=>k.startsWith(`${d}-`)).length;}
  isDifficultyOpen(d){return d==='Easy'||(d==='Hard'&&this.countDone('Easy')>=20)||(d==='Master'&&this.countDone('Hard')>=20);}
  canPlay(d,l){return this.isDifficultyOpen(d)&&Number.isInteger(l)&&l>=1&&l<=20&&(l===1||!!this.completed[this.key(d,l-1)]);}
  start(d,l){if(!this.canPlay(d,l))return false;this.difficulty=d;this.level=l;this.lives=3;this.hintStage=0;return true;}
  currentPuzzle(){return this.puzzles[this.difficulty][this.level-1];}
  answer(value){if(value===this.currentPuzzle().answer){this.completed[this.key()]={stars:3};this.save();return'complete';}this.lives=Math.max(0,this.lives-1);this.save();return this.lives===0?'gameover':'wrong';}
  useHint(){if(this.hints<=0||this.hintStage>=3)return false;this.hints--;this.hintStage++;this.save();return true;}
  claimDailyHint(){if(!navigator.onLine)return'offline';const now=new Date();const day=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;if(localStorage.getItem('sequenceIQ.dailyHint')===day)return'claimed';localStorage.setItem('sequenceIQ.dailyHint',day);this.hints++;this.save();return'claimed-now';}
}
