import { GameModel } from '../Model/GameModel.js';
import { SplashView } from '../View/SplashView.js';
import { HomeView } from '../View/HomeView.js';
import { DifficultyView } from '../View/DifficultyView.js';
import { LevelMapView } from '../View/LevelMapView.js';
import { GameplayView } from '../View/GameplayView.js';
import { LevelCompleteView } from '../View/LevelCompleteView.js';
import { GameOverView } from '../View/GameOverView.js';
import { SettingsView } from '../View/SettingsView.js';
import { ShopView } from '../View/ShopView.js';
import { AchievementsView } from '../View/AchievementsView.js';
import { StatsView } from '../View/StatsView.js';
import { ComingSoonView } from '../View/ComingSoonView.js';
export class AppController {
 constructor(root){this.root=root;this.model=new GameModel();this.render()}
 async init(){await this.model.loadPuzzles();this.bind();this.show('splashScreen');setTimeout(()=>this.show('homeScreen'),1500)}
 render(){this.root.innerHTML=[SplashView(),HomeView(),DifficultyView(),LevelMapView(),GameplayView(),LevelCompleteView(),GameOverView(),SettingsView(),ShopView(),AchievementsView(),StatsView(),ComingSoonView()].join('')}
 show(id){this.root.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id)?.classList.add('active');window.scrollTo(0,0)}
 bind(){this.root.addEventListener('click',e=>{const t=e.target.closest('[data-action]');if(t)this.action(t.dataset.action,t);const o=e.target.closest('.option');if(o&&!o.disabled&&!o.classList.contains('removed'))this.choose(Number(o.dataset.value))});const m=document.getElementById('musicToggle'),s=document.getElementById('soundToggle');if(m)m.onchange=e=>{this.model.music=e.target.checked;this.model.save()};if(s)s.onchange=e=>{this.model.sound=e.target.checked;this.model.save()}}
 action(a,el){if(a==='home')return this.show('homeScreen');if(a==='play'){this.renderDifficulty();return this.show('difficultyScreen')}if(a==='difficulty')return this.show('difficultyScreen');if(a==='levels')return this.openLevels();if(a==='settings'){this.show('settingsScreen');document.getElementById('musicToggle').checked=this.model.music;document.getElementById('soundToggle').checked=this.model.sound;return}if(a==='shop'){this.show('shopScreen');return}if(a==='stats'){this.renderStats();return this.show('statsScreen')}if(a==='achievements'){this.renderAchievements();return this.show('achievementsScreen')}if(a==='coming')return this.show('comingScreen');if(a==='restart'||a==='retry')return this.start(this.model.difficulty,this.model.level);if(a==='hint')return this.hint();if(a==='next')return this.start(this.model.difficulty,this.model.level+1);if(a==='skip'){document.getElementById('feedback').textContent='Complete this level to unlock the next level.';return}if(a==='dailyHint'){const r=this.model.claimDailyHint();alert(r==='offline'?'Internet connection required.':r==='claimed'?'Today’s free hint is already collected.':'Daily hint collected!');return}if(a==='reset'){if(confirm('Reset all Sequence IQ progress?')){localStorage.clear();location.reload()}return}if(a==='shopHint'){this.model.hints+=5;this.model.save();alert('5 hints added.');return}if(a==='start'&&el)return this.start(this.model.difficulty,Number(el.dataset.level))}
 openLevels(){this.renderDifficulty();this.show('levelsScreen');this.renderMap()}
 renderDifficulty(){const root=document.getElementById('difficultyCards');root.innerHTML='';for(const d of ['Easy','Hard','Master']){const open=this.model.isDifficultyOpen(d),count=this.model.countDone(d),b=document.createElement('button');b.className=`difficulty-card ${d.toLowerCase()} ${open?'':'locked'}`;b.disabled=!open;b.innerHTML=`<span class="difficulty-icon">${d==='Easy'?'🌱':d==='Hard'?'🔥':'👑'}</span><span><strong>${d}</strong><small>20 Levels</small><em>${open?'Start your journey':'Complete previous difficulty to unlock'}</em></span><b>›</b>`;b.onclick=()=>{if(open){this.model.difficulty=d;this.model.level=1;this.show('levelsScreen');this.renderMap()}};root.appendChild(b)}}
 renderMap(){const root=document.getElementById('levelMap');document.getElementById('mapTitle').textContent=`${this.model.difficulty} Levels`;document.getElementById('mapHints').textContent=this.model.hints;root.innerHTML='';for(let row=0;row<5;row++){const r=document.createElement('div');r.className=`map-row ${row%2?'reverse':''}`;const ids=row%2?[4*row+4,4*row+3,4*row+2,4*row+1]:[4*row+1,4*row+2,4*row+3,4*row+4];ids.forEach(i=>{const done=!!this.model.completed[this.model.key(this.model.difficulty,i)],playable=this.model.canPlay(this.model.difficulty,i),b=document.createElement('button');b.className=`level-node ${done?'completed ':''}${playable&&!done?'current ':''}${!playable?'locked':''}`;b.disabled=!playable;b.dataset.action='start';b.dataset.level=i;b.innerHTML=`<span class="node">${playable?i:'🔒'}</span><span class="level-stars">${done?'★ ★ ★':''}</span>${playable&&!done?'<span class="current-label">CURRENT</span>':''}`;r.appendChild(b)});root.appendChild(r)}}
 start(d,l){if(!this.model.start(d,l))return;this.show('gameScreen');this.renderPuzzle()}
 renderPuzzle(){const p=this.model.currentPuzzle();document.getElementById('levelLabel').textContent=`Level ${this.model.level}`;document.getElementById('puzzleNumber').textContent=`PUZZLE ${String(this.model.level).padStart(2,'0')}`;document.getElementById('livesLabel').textContent='♥'.repeat(this.model.lives);document.getElementById('hintBadge').textContent=this.model.hints;document.getElementById('sequence').innerHTML=p.sequence.map(n=>`<span class="${n===null?'missing':''}">${n===null?'?':n}</span>`).join('');document.getElementById('options').innerHTML=p.options.map(n=>`<button class="option" data-value="${n}">${n}</button>`).join('');document.getElementById('hintButton').disabled=this.model.hints<=0||this.model.hintStage>=3;document.getElementById('feedback').textContent=''}
 choose(v){const r=this.model.answer(v);if(r==='complete'){this.show('completeScreen');document.getElementById('completeText').textContent=`Level ${this.model.level}`;document.getElementById('completeHints').textContent=this.model.hintStage;document.getElementById('nextLevelButton').style.display='block'}else if(r==='gameover')this.show('gameOverScreen');else{document.getElementById('livesLabel').textContent='♥'.repeat(this.model.lives);document.getElementById('feedback').textContent='Not quite — try another option.'}}
 hint(){if(!this.model.useHint())return;const p=this.model.currentPuzzle(),v=[...document.querySelectorAll('.option:not(.removed)')];if(this.model.hintStage===1)v.filter(b=>Number(b.dataset.value)!==p.answer).slice(0,2).forEach(b=>b.classList.add('removed'));if(this.model.hintStage===2)[...document.querySelectorAll('.option:not(.removed)')].filter(b=>Number(b.dataset.value)!==p.answer).forEach(b=>b.classList.add('removed'));if(this.model.hintStage===3){document.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(Number(b.dataset.value)===p.answer)b.classList.add('correct')});document.getElementById('feedback').textContent='Answer revealed.'}document.getElementById('hintBadge').textContent=this.model.hints}
 renderStats(){const done=Object.keys(this.model.completed).length,stars=Object.values(this.model.completed).reduce((n,v)=>n+(v?.stars||3),0);document.getElementById('statsCard').innerHTML=`<div class="stat"><span>Total Levels</span><b>60</b></div><div class="stat"><span>Completed</span><b>${done}</b></div><div class="stat"><span>Stars Collected</span><b>${stars}</b></div><div class="stat"><span>Hints Used</span><b>0</b></div><div class="stat"><span>Total Play Time</span><b>00:25</b></div><div class="quote-card">“Discipline Today<br>Brighter Tomorrow”</div>`}
 renderAchievements(){const done=Object.keys(this.model.completed).length,items=[['First Step','Complete Level 1',done>=1],['Rising Mind','Complete 10 Levels',done>=10],['Sequence Master','Complete 20 Levels',done>=20],['Pattern Expert','Complete 40 Levels',done>=40],['Genius','Complete All 60 Levels',done>=60]];document.getElementById('achievementList').innerHTML=items.map(([t,s,ok])=>`<div class="achievement ${ok?'unlocked':''}"><span>${ok?'🏅':'🔒'}</span><div><b>${t}</b><small>${s}</small></div></div>`).join('')}
}
