import SwiftUI
import Combine

struct Puzzle { let sequence:[Int?]; let answer:Int; let options:[Int] }
enum Difficulty:String,CaseIterable { case easy="Easy",hard="Hard",master="Master" }
enum Screen { case splash,home,levels,game,complete,gameOver }
final class GameModel:ObservableObject {
 @Published var difficulty:Difficulty = .easy; @Published var level=1; @Published var lives=3; @Published var hints=3; @Published var completed:Set<String>=[]; @Published var hintStage=0; @Published var screen:Screen = .splash; @Published var message=""
 init(){if let d=UserDefaults.standard.data(forKey:"completed"),let s=try? JSONDecoder().decode(Set<String>.self,from:d){completed=s};let h=UserDefaults.standard.object(forKey:"hints") as? Int;if let h,h>0{hints=h}}
 func save(){if let d=try? JSONEncoder().encode(completed){UserDefaults.standard.set(d,forKey:"completed")};UserDefaults.standard.set(hints,forKey:"hints")}
 func open(_ d:Difficulty)->Bool{d == .easy || (d == .hard && completed.filter{$0.hasPrefix("Easy-")}.count>=20) || (d == .master && completed.filter{$0.hasPrefix("Hard-")}.count>=20)}
 func canPlay(_ d:Difficulty,_ l:Int)->Bool{open(d)&&l>=1&&l<=20&&(l==1||completed.contains("\(d.rawValue)-\(l-1)")||completed.contains("\(d.rawValue)-\(l)"))}
 func start(_ d:Difficulty,_ l:Int){guard canPlay(d,l) else{return};difficulty=d;level=l;lives=3;hintStage=0;message="";screen = .game}
 func puzzle()->Puzzle{let a=level+1;switch difficulty{case .easy:return Puzzle(sequence:[a,a+2,a+4,a+6,nil,a+10],answer:a+8,options:[a+8,a+12,a+4,a+14]);case .hard:return Puzzle(sequence:[a,a*2,a*4,a*8,nil,a*32],answer:a*16,options:[a*16,a*12,a*24,a*32]);case .master:return Puzzle(sequence:[a,a+3,a+8,a+15,nil,a+35],answer:a+24,options:[a+24,a+31,a+21,a+36])}}
 func answer(_ n:Int){guard screen == .game else{return};if n==puzzle().answer{completed.insert("\(difficulty.rawValue)-\(level)");save();screen = .complete}else{lives-=1;message=lives==0 ? "Game Over" : "Try again.";if lives==0{screen = .gameOver}}}
 func retry(){start(difficulty,level)}
 func next(){guard level<20,canPlay(difficulty,level+1) else{return};start(difficulty,level+1)}
 func hint(){guard hints>0 && hintStage<3 else{return};hints-=1;hintStage+=1;save()}
}
@main struct SequenceIQApp:App{var body:some Scene{WindowGroup{ContentView()}}}
struct ContentView:View{@StateObject var game=GameModel();var body:some View{ZStack{switch game.screen{case .splash:SplashView();case .home:HomeView(game:game);case .levels:LevelsView(game:game);case .game:GameView(game:game);case .complete:CompleteView(game:game);case .gameOver:GameOverView(game:game)}}.task{try? await Task.sleep(for:.seconds(1.5));if game.screen == .splash{game.screen = .home}}}}
struct SplashView:View{var body:some View{VStack(spacing:16){Text("🧠").font(.system(size:70));Text("SEQUENCE\nIQ").font(.system(size:44,weight:.black)).multilineTextAlignment(.center);Text("Find the Pattern\nBoost Your Brain").multilineTextAlignment(.center);ProgressView("Loading...")}}}
struct HomeView:View{@ObservedObject var game:GameModel;var body:some View{VStack(spacing:18){Spacer();Text("🧠").font(.system(size:70));Text("SEQUENCE\nIQ").font(.system(size:44,weight:.black)).multilineTextAlignment(.center);Text("Find the Pattern\nBoost Your Brain").multilineTextAlignment(.center);Button("▶  PLAY"){game.screen = .levels}.buttonStyle(.borderedProminent);HStack{Button("SHOP"){};Button("PLAY"){game.screen = .levels};Button("SOON"){} }.buttonStyle(.bordered);Text("“Small Steps\nMake a Sharper Mind”").multilineTextAlignment(.center);Spacer()}.padding()}}
struct LevelsView:View{@ObservedObject var game:GameModel;var body:some View{ScrollView{VStack(spacing:18){HStack{Button("‹"){game.screen = .home};Spacer();Text("\(game.difficulty.rawValue) Levels").font(.title2.bold());Spacer();Text("💡 \(game.hints)")};HStack{ForEach(Difficulty.allCases,id:\.self){d in Button(d.rawValue){if game.open(d){game.difficulty=d}}.disabled(!game.open(d))}}.buttonStyle(.borderedProminent);ForEach(1...20,id:\.self){i in let playable=game.canPlay(game.difficulty,i);Button("\(i)\n\(game.completed.contains("\(game.difficulty.rawValue)-\(i)") ? "★ ★ ★" : playable ? "CURRENT" : "🔒")"){game.start(game.difficulty,i)}.disabled(!playable).frame(maxWidth:.infinity).buttonStyle(.bordered)}}.padding()}}}
struct GameView:View{@ObservedObject var game:GameModel;var body:some View{let p=game.puzzle();VStack(spacing:16){HStack{Button("‹"){game.screen = .levels};Spacer();Text("\(game.difficulty.rawValue) · Level \(game.level)");Spacer();Text(String(repeating:"♥",count:game.lives))};Text("Find the next number").font(.headline);HStack{ForEach(Array(p.sequence.enumerated()),id:\.offset){_,n in Text(n.map(String.init) ?? "?").frame(maxWidth:.infinity).padding().background(.thinMaterial).clipShape(RoundedRectangle(cornerRadius:10))}};ForEach(p.options,id:\.self){n in Button("\(n)"){game.answer(n)}.frame(maxWidth:.infinity)};HStack{Button("💡 Hint (\(game.hints))"){game.hint()}.disabled(game.hints==0);Button("↻ Restart"){game.retry()};Button("» Skip"){game.message="Complete this level to unlock the next level."}};Text(game.message).foregroundStyle(.secondary);Spacer()}.padding()}}
struct CompleteView:View{@ObservedObject var game:GameModel;var body:some View{VStack(spacing:18){Spacer();Text("🏆").font(.system(size:70));Text("LEVEL COMPLETE").font(.caption.bold());Text("Excellent!").font(.largeTitle.bold());Text("★ ★ ★").font(.title).foregroundStyle(.yellow);if game.level<20{Button("NEXT LEVEL ›"){game.next()}.buttonStyle(.borderedProminent)};Button("LEVEL MAP"){game.screen = .levels};Button("HOME"){game.screen = .home};Spacer()}.padding()}}
struct GameOverView:View{@ObservedObject var game:GameModel;var body:some View{VStack(spacing:18){Spacer();Text("💥").font(.system(size:70));Text("GAME OVER").font(.caption.bold());Text("Try Again!").font(.largeTitle.bold());Text("You used all 3 lives.");Button("↻ RETRY"){game.retry()}.buttonStyle(.borderedProminent);Button("LEVEL MAP"){game.screen = .levels};Button("HOME"){game.screen = .home};Spacer()}.padding()}}