const PUZZLES={Easy:Array.from({length:20},(_,i)=>{const a=2+i;return[a,a+2,a+4,a+6,null,a+10,[a+12,a+4,a+14,a+2]]}),Hard:Array.from({length:20},(_,i)=>{const a=2+i;return[a,a*2,a*4,a*8,null,a*32,[a*16,a*12,a*24,a*32]]}),Master:Array.from({length:20},(_,i)=>{const a=2+i;return[a,a+3,a+8,a+15,null,a+35,[a+31,a+21,a+36,a+24]]})};
const state={difficulty:'Easy',level:1,lives:3,hints:Number(localStorage.getItem('sequenceIQ.hints')||3),completed:JSON.parse(localStorage.getItem('sequenceIQ.completed')||'{}'),hintStage:0,music:localStorage.getItem('sequenceIQ.music')!=='false',sound:localStorage.getItem('sequenceIQ.sound')!=='false'};
const $=id=>document.getElementById(id),key=()=>`${state.difficulty}-${state.level}`;
function save(){localStorage.setItem('sequenceIQ.completed',JSON.stringify(state.completed));localStorage.setItem('sequenceIQ.hints',state.hints);localStorage.setItem('sequenceIQ.music',state.music);localStorage.setItem('sequenceIQ.sound',state.sound)}
function show(screen){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(screen).classList.add('active')}
function unlocked(d){if(d==='Easy')return true;const p=d==='Hard'?'Easy':'Hard';return Object.keys(state.completed).filter(k=>k.startsWith(`${p}-`)).length>=20}
function renderTabs(){const tab=document.querySelector('.tab.active')?.dataset.tab||'play',c=$('tabContent');if(tab==='play')c.innerHTML='<strong>Play</strong><p>Complete all 20 Easy levels to unlock Hard, then all 20 Hard levels to unlock Master.</p>';if(tab==='shop')c.innerHTML=`<strong>Shop</strong><p>Daily free hint: ${navigator.onLine?'available online once per day.':'internet connection required.'}</p><button id="dailyHint" class="secondary-button">Collect Daily Hint</button>`;if(tab==='coming')c.innerHTML='<strong>Coming Soon</strong><p>Future Sequence IQ content and features will appear here.</p>';if($('dailyHint'))$('dailyHint').onclick=collectDailyHint}
function collectDailyHint(){if(!navigator.onLine)return alert('Internet connection required.');const today=new Date().toISOString().slice(0,10);if(localStorage.getItem('sequenceIQ.dailyHint')===today)return alert('Today’s free hint is already collected.');localStorage.setItem('sequenceIQ.dailyHint',today);state.hints++;save();alert('Daily hint collected.');renderTabs()}
function renderLevels(){const root=$('difficultyGroups');root.innerHTML='';['Easy','Hard','Master'].forEach(d=>{const open=unlocked(d),done=Object.keys(state.completed).filter(k=>k.startsWith(`${d}-`)).length,s=document.createElement('section');s.className='difficulty';s.innerHTML=`<div class="difficulty-header"><h3>${d}</h3><span>${open?`${done}/20 completed`:'Locked'}</span></div><div class="level-grid"></div>`;const g=s.querySelector('.level-grid');for(let i=1;i<=20;i++){const b=document.createElement('button');b.className='level';b.textContent=i;if(state.completed[`${d}-${i}`])b.classList.add('completed');if(!open){b.classList.add('locked');b.disabled=true}else b.onclick=()=>startLevel(d,i);g.appendChild(b)}root.appendChild(s)})}
function startLevel(d,l){state.difficulty=d;state.level=l;state.lives=3;state.hintStage=0;show('gameScreen');renderPuzzle()}
function renderPuzzle(){const p=PUZZLES[state.difficulty][state.level-1],answer=state.difficulty==='Easy'?p[0]+8:state.difficulty==='Hard'?p[0]*16:p[0]+24;let choices=[answer,...p[6]].filter((v,i,a)=>a.indexOf(v)===i).slice(0,4);while(choices.length<4)choices.push(answer+choices.length+3);$('levelLabel').textContent=`${state.difficulty} · Level ${state.level}`;$('puzzleNumber').textContent=`PUZZLE ${String(state.level).padStart(2,'0')}`;$('livesLabel').textContent='♥'.repeat(state.lives)+'♡'.repeat(3-state.lives);$('progressBar').style.width=`${state.level/20*100}%`;$('hintBalance').textContent=`Hints: ${state.hints}`;$('sequence').innerHTML=p.slice(0,6).map(n=>`<span class="${n===null?'missing':''}">${n??'?'}</span>`).join('');$('options').innerHTML=choices.map(n=>`<button class="option" data-value="${n}">${n}</button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>choose(Number(b.dataset.value),answer,b));$('hintButton').disabled=state.hints<=0||state.hintStage>=3;$('feedback').textContent=''}
function choose(value,answer,b){if(value===answer){b.classList.add('correct');state.completed[key()]=true;save();setTimeout(showComplete,350)}else{b.classList.add('wrong');b.disabled=true;state.lives--;$('livesLabel').textContent='♥'.repeat(state.lives)+'♡'.repeat(3-state.lives);$('feedback').textContent='Not quite. Try another option.';if(state.lives<=0)setTimeout(()=>show('gameOverScreen'),350)}}
function useHint(){if(state.hints<=0||state.hintStage>=3)return;state.hints--;state.hintStage++;save();const b=[...document.querySelectorAll('.option:not(.wrong):not(.correct)')];if(state.hintStage===1)b.slice(0,2).forEach(x=>x.classList.add('removed'));if(state.hintStage===2)b.filter(x=>!x.classList.contains('removed')).slice(0,1).forEach(x=>x.classList.add('removed'));if(state.hintStage===3){$('feedback').textContent='The final answer is revealed.';document.querySelectorAll('.option:not(.removed)').forEach(x=>x.classList.add('correct'))}$('hintBalance').textContent=`Hints: ${state.hints}`;$('hintButton').disabled=state.hints<=0||state.hintStage>=3}
function showComplete(){$('completeText').textContent=state.level===20?`${state.difficulty} complete. Great job!`:`You solved ${state.difficulty} Level ${state.level}.`;$('nextLevelButton').style.display=state.level<20?'block':'none';show('completeScreen')}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');renderTabs()});$('openPlayButton').onclick=()=>{show('levelsScreen');renderLevels()};$('backHomeButton').onclick=()=>show('homeScreen');$('backLevelsButton').onclick=()=>{show('levelsScreen');renderLevels()};$('retryButton').onclick=()=>startLevel(state.difficulty,state.level);$('resultLevelsButton').onclick=()=>{show('levelsScreen');renderLevels()};$('resultHomeButton').onclick=()=>show('homeScreen');$('completeLevelsButton').onclick=()=>{show('levelsScreen');renderLevels()};$('nextLevelButton').onclick=()=>startLevel(state.difficulty,state.level+1);$('hintButton').onclick=useHint;$('settingsButton').onclick=()=>{$('settingsModal').classList.remove('hidden');$('musicToggle').checked=state.music;$('soundToggle').checked=state.sound};$('closeSettingsButton').onclick=()=>$('settingsModal').classList.add('hidden');$('musicToggle').onchange=e=>{state.music=e.target.checked;save()};$('soundToggle').onchange=e=>{state.sound=e.target.checked;save()};window.addEventListener('online',renderTabs);window.addEventListener('offline',renderTabs);renderTabs();