let PUZZLES={Easy:[],Hard:[],Master:[]};
const state={difficulty:'Easy',level:1,lives:3,hints:Number(localStorage.getItem('sequenceIQ.hints')??3),completed:JSON.parse(localStorage.getItem('sequenceIQ.completed')||'{}'),hintStage:0,music:localStorage.getItem('sequenceIQ.music')!=='false',sound:localStorage.getItem('sequenceIQ.sound')!=='false'};
const $=id=>document.getElementById(id);const key=()=>`${state.difficulty}-${state.level}`;
async function loadPuzzles(){const text=await fetch('Puzzles.txt').then(r=>{if(!r.ok)throw Error('Puzzles.txt unavailable');return r.text()});text.split(/\r?\n/).forEach(line=>{line=line.trim();if(!line||line.startsWith('#'))return;const [id,difficulty,seq,opts,answer]=line.split('|');if(!id||!difficulty||!seq||!opts||answer===undefined)return;const p={id,sequence:seq.split(',').map(x=>x.trim()==='?'?null:Number(x)),options:opts.split(',').map(Number),answer:Number(answer)};(PUZZLES[difficulty]??=[]).push(p);});if(['Easy','Hard','Master'].some(d=>PUZZLES[d].length!==20))throw Error('Incomplete puzzle set');}
function save(){localStorage.setItem('sequenceIQ.completed',JSON.stringify(state.completed));localStorage.setItem('sequenceIQ.hints',state.hints);localStorage.setItem('sequenceIQ.music',state.music);localStorage.setItem('sequenceIQ.sound',state.sound)}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0)}
function countDone(d){return Object.keys(state.completed).filter(k=>k.startsWith(d+'-')).length}
function difficultyOpen(d){return d==='Easy'||(d==='Hard'&&countDone('Easy')>=20)||(d==='Master'&&countDone('Hard')>=20)}
function canPlay(d,l){if(!difficultyOpen(d)||l<1||l>20)return false;return l===1||!!state.completed[`${d}-${l-1}`]||!!state.completed[`${d}-${l}`]}
function renderDifficulty(){const root=$('difficultyPicker');root.innerHTML='';['Easy','Hard','Master'].forEach(d=>{const b=document.createElement('button');b.textContent=difficultyOpen(d)?`${d} ${countDone(d)}/20`:`🔒 ${d}`;b.className=(d===state.difficulty?'active ':'')+(difficultyOpen(d)?'':'locked');b.onclick=()=>{if(!difficultyOpen(d))return;state.difficulty=d;state.level=1;renderDifficulty();renderMap()};root.appendChild(b)});$('mapTitle').textContent=`${state.difficulty} Levels`;$('mapHints').textContent=state.hints}
function renderMap(){const root=$('levelMap');root.innerHTML='';for(let row=0;row<5;row++){const r=document.createElement('div');r.className='map-row '+(row%2?'reverse':'');const ids=row%2?[4*row+4,4*row+3,4*row+2,4*row+1]:[4*row+1,4*row+2,4*row+3,4*row+4];ids.forEach(i=>{const done=!!state.completed[`${state.difficulty}-${i}`],current=canPlay(state.difficulty,i)&&!done,playable=canPlay(state.difficulty,i),b=document.createElement('button');b.className='level-node '+(done?'completed ':'')+(current?'current ':'')+(!playable?'locked':'');b.disabled=!playable;b.innerHTML=`<span class="node">${playable?i:'🔒'}</span><span class="level-stars">${done?'★ ★ ★':''}</span>${current?'<span class="current-label">CURRENT</span>':''}`;b.onclick=()=>startLevel(state.difficulty,i);r.appendChild(b)});root.appendChild(r)} }
function startLevel(d,l){if(!canPlay(d,l))return;state.difficulty=d;state.level=l;state.lives=3;state.hintStage=0;show('gameScreen');renderPuzzle()}
function renderPuzzle(){const p=PUZZLES[state.difficulty][state.level-1];$('levelLabel').textContent=`${state.difficulty} · Level ${state.level}`;$('puzzleNumber').textContent=`PUZZLE ${String(state.level).padStart(2,'0')}`;$('livesLabel').textContent='♥'.repeat(state.lives)+'♡'.repeat(3-state.lives);$('progressBar').style.width=`${state.level/20*100}%`;$('hintBadge').textContent=state.hints;$('sequence').innerHTML=p.sequence.map(n=>`<span class="${n===null?'missing':''}">${n===null?'?':n}</span>`).join('');$('options').innerHTML=p.options.map(n=>`<button class="option" data-value="${n}">${n}</button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>choose(Number(b.dataset.value),p.answer,b));$('hintButton').disabled=state.hints<=0||state.hintStage>=3;$('feedback').textContent=''}
function choose(value,answer,b){if(value===answer){b.classList.add('correct');state.completed[key()]=true;save();setTimeout(showComplete,300)}else{b.classList.add('wrong');b.disabled=true;state.lives--;save();$('livesLabel').textContent='♥'.repeat(state.lives)+'♡'.repeat(3-state.lives);$('feedback').textContent='Not quite — try another option.';if(state.lives<=0)setTimeout(()=>show('gameOverScreen'),450)}}
function useHint(){if(state.hints<=0||state.hintStage>=3)return;const p=PUZZLES[state.difficulty][state.level-1],remaining=[...document.querySelectorAll('.option:not(.wrong):not(.removed)')];state.hints--;state.hintStage++;save();if(state.hintStage===1)remaining.filter(b=>Number(b.dataset.value)!==p.answer).slice(0,2).forEach(b=>b.classList.add('removed'));if(state.hintStage===2)[...document.querySelectorAll('.option:not(.wrong):not(.removed)')].filter(b=>Number(b.dataset.value)!==p.answer).forEach(b=>b.classList.add('removed'));if(state.hintStage===3){const a=p.answer;document.querySelectorAll('.option').forEach(b=>{if(Number(b.dataset.value)===a)b.classList.add('correct')});$('feedback').textContent='Answer revealed.'}$('hintBadge').textContent=state.hints;$('hintButton').disabled=state.hints<=0||state.hintStage>=3}
function showComplete(){$('completeText').textContent=state.level===20?`${state.difficulty} complete!`:`You cleared ${state.difficulty} Level ${state.level}.`;$('nextLevelButton').style.display=state.level<20?'block':'none';show('completeScreen')}
function openInfo(tab){if(tab==='shop'){$('infoTitle').textContent='🛒 Shop';$('infoText').textContent=navigator.onLine?'Collect one free hint each day while online.':'Connect to the internet to collect today’s free hint.';$('dailyHint').style.display='block';$('infoModal').classList.remove('hidden')}else if(tab==='play'){show('levelsScreen');renderDifficulty();renderMap()}else{$('infoTitle').textContent='✦ Coming Soon';$('infoText').textContent='New Sequence IQ content and features are coming soon.';$('dailyHint').style.display='none';$('infoModal').classList.remove('hidden')}}
function collectDailyHint(){if(!navigator.onLine)return alert('Internet connection required.');const today=new Date().toISOString().slice(0,10);if(localStorage.getItem('sequenceIQ.dailyHint')===today)return alert('Today’s free hint is already collected.');localStorage.setItem('sequenceIQ.dailyHint',today);state.hints++;save();renderDifficulty();alert('Daily hint collected!');$('infoModal').classList.add('hidden')}
function init(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>openInfo(b.dataset.tab));$('openPlayButton').onclick=()=>{show('levelsScreen');renderDifficulty();renderMap()};$('homeButton').onclick=()=>show('homeScreen');$('backHomeButton').onclick=()=>show('homeScreen');$('backLevelsButton').onclick=()=>{show('levelsScreen');renderDifficulty();renderMap()};$('restartButton').onclick=()=>startLevel(state.difficulty,state.level);$('skipButton').onclick=()=>{if(state.level<20 && canPlay(state.difficulty,state.level+1))startLevel(state.difficulty,state.level+1)};$('hintButton').onclick=useHint;$('retryButton').onclick=()=>startLevel(state.difficulty,state.level);$('resultLevelsButton').onclick=()=>{show('levelsScreen');renderDifficulty();renderMap()};$('resultHomeButton').onclick=()=>show('homeScreen');$('completeLevelsButton').onclick=()=>{show('levelsScreen');renderDifficulty();renderMap()};$('completeHomeButton').onclick=()=>show('homeScreen');$('nextLevelButton').onclick=()=>{if(state.level<20)startLevel(state.difficulty,state.level+1)};$('settingsButton').onclick=()=>{$('settingsModal').classList.remove('hidden');$('musicToggle').checked=state.music;$('soundToggle').checked=state.sound};$('closeSettingsButton').onclick=()=>$('settingsModal').classList.add('hidden');$('closeInfoButton').onclick=()=>$('infoModal').classList.add('hidden');$('dailyHint').onclick=collectDailyHint;$('musicToggle').onchange=e=>{state.music=e.target.checked;save()};$('soundToggle').onchange=e=>{state.sound=e.target.checked;save()};renderDifficulty();renderMap()}
loadPuzzles().then(init).catch(e=>{console.error(e);document.body.innerHTML='<div style="padding:30px;color:white;background:#061737;font-family:system-ui"><h2>Sequence IQ</h2><p>Could not load the puzzle data. Please refresh the page.</p></div>'});